[package]
name = "reverence"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib","rlib"]

[[bin]]
name = "pvz"
path = "src/main.rs"


[dependencies]
bytemuck = "1.13.0"
cfg-if = "1"
env_logger = "0.10.0"
froggy = "0.4.4"
ggrs = "0.9.3"
glam = "0.22.0"
log = "0.4.17"
pollster = "0.3.0"
tokio = { version = "1", features = ["full"] }
wgpu = "0.15.0"
winit = "0.27.5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
wgpu = { version = "0.15", features = ["webgl"]}
wasm-bindgen = "0.2.76"
wasm-bindgen-futures = "0.4.30"
web-sys = { version = "0.3.53", features = [
    "Document",
    "Window",
    "Element",
]}
